server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true #开 启文件上传
      max-file-size: 10MB # 限制文件上传大小为10M
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  data:
    elasticsearch:
      repositories:
        enabled: true # 开启ES仓库配置，自动为仓库接口生成实现类
    mongodb:
      host: localhost # MongoDB的连接地址
      port: 27017 # MongoDB的连接端口号
      database: mall-port # MongoDB的连接的数据库
  elasticsearch:
    uris: http://localhost:9200 # ES的连接地址及端口号
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-returns: true #消息发送到队列确认
    publisher-confirm-type: simple #消息发送到交换器确认

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
    - classpath*:/mapper/**/*.xml

minio:
  endpoint: http://localhost:9000 # MinIO服务所在地址
  bucketName: mall # 存储桶名称
  accessKey: minioadmin # 访问的key
  secretKey: minioadmin # 访问的秘钥

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/**
      - /esProduct/**
      - /member/readHistory/**
      - /order/**
      - /minio/**