server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-returns: true #消息发送到队列确认
    publisher-confirm-type: simple #消息发送到交换器确认
